### ISSUE TITLE
cargointake Notes

### ISSUE THREAD

**Issue by MattHalsmer** [Team3176/Code_2019#1]
cargointake.java  Notes from M. Halsmer 03-MAR
Overall makes sense and pretty easy to follow.  A few observations. 
  - Spit has negative value.  I thought it went the same direction as intake. 
  - Should intake function be included on deploy...
  - How is intake stopped when ball is actually grabbed. Is that managed in different code?   
  - Should the stowedLimit and deployLimit be setup as Interrupts? 
  - class timer has issues.  doesn't look like its used...

**Comment by hmccarty** [comment]
The spit, at least for the cargo ship, will reverse due to position of the intake when deploying. Other issues were fixed at competition. Thanks for the help!
